[flavor]
name = "prusa"
version = "0.1"

[[commands]]
name = "M250"
pattern = "^M250( .*)?$"
description_short = "Prusa Buddy example command M250"
description_long = "M250 is a Buddy-specific diagnostic command used to ... (long description placeholder)"

[[commands.parameters]]
name = "S"
type = "int"
required = false
description = "Example parameter S"

[[commands]]
name = "G28"
pattern = "^G28( .*)?$"
description_short = "Home axes"
description_long = "G28 homes the printer axes. On Prusa firmware, G28 has optional parameters to home specific axes."

[[commands]]
name = "G0"
pattern = "^G0( .*)?$"
description_short = "Rapid linear move"
description_long = "G0 performs a rapid, non-extruding linear move to the specified coordinates. Parameters: X, Y, Z, F (feedrate)."

[[commands]]
name = "G1"
pattern = "^G1( .*)?$"
description_short = "Controlled linear move"
description_long = "G1 moves the toolhead linearly while feeding filament (if applicable). Parameters: X, Y, Z, E, F."

[[commands]]
name = "G91"
pattern = "^G91( .*)?$"
description_short = "Set to relative positioning"
description_long = "G91 switches the coordinate system to relative positioning. Subsequent moves are interpreted as offsets."

[[commands]]
name = "G92"
pattern = "^G92( .*)?$"
description_short = "Set current position"
description_long = "G92 sets the current position to the given coordinates without moving the machine. Parameters: X, Y, Z, E."
